spring.application.name=purchase_order

spring.datasource.url=jdbc:postgresql://localhost:5432/kanishka_purchase_order
spring.datasource.username=postgres
spring.datasource.password=Rup@@.123$
spring.jpa.hibernate.ddl-auto=update

# --- OAUTH2 CONFIGURATION ---
# Registration for Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# (Optional) If you want to add GitHub as well
# spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
# spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET